### ISSUE TITLE
Allow merge to stable when required

### ISSUE THREAD

**Issue by jking-aus** [sigp/anchor#52]
CI checks to prevent merging PRs to stable branch which is intended behaviour generally, but do need to be able to allow this when required

**Comment by magick93** [comment]
Hi @AgeManning 

I suspect this issue is due to some applied [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) but I'm unable to see them due to permissions. 

Are you able to give me, at least, read permissions to this repo? I believe that is different from public, and should allow me to view the rules the repo.

**Comment by AgeManning** [comment]
I've fixed the permissions. 

But I think this might be a non-issue. 

Our procedure should just be to merge to unstable with PRs, then manually merge to stable and we're all good

**Comment by jking-aus** [comment]
closed with PR 54
